version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - TZ=Japan
    volumes:
      - .:/go/src/github.com/edm20627/go_line_reservation
    ports:
      - 8080:8080